# Enable Dependabot for all forked repos
name: EnableDependabot

on:
  push:
    paths:
      - .github/workflows/dependabot-updates.yml

  #schedule:
     #- cron: '*/60 * * * *'
     #- cron: '1 */1 * * *'

  workflow_dispatch:

env:
  numberOfReposToDo: 100
  numberOfReposToDoRepoInfo: 100

jobs:
  enable-em-all:
    concurrency: there-can-be-only-one-dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current actions list
        run: |
          curl "${{ secrets.BLOB_SAS_TOKEN }}" > actions.json
          
      - name: Get App Token
        id: get_workflow_token
        uses: rajbos-actions/workflow-application-token-action@v2.1.0
        with:
          application_id: 264650
          application_private_key: ${{ secrets.Automation_App_Key }}
          organization: actions-marketplace-validations
          
      - shell: pwsh
        name: Gotta enable 'em all
        run: |
           $existingForks=(cat status.json | ConvertFrom-Json)
           Write-Host "Found [$($existingForks.Length)] actions in the status file"
           Install-Module -Name PSGraphQL -Repository PSGallery -Scope CurrentUser -Allowclobber -Force
           Install-Module -name powershell-yaml -Force -Repository PSGallery -Scope CurrentUser -Allowclobber

           # fork repos and load Dependabot status
           ./.github/workflows/dependabot-updates.ps1 -actions $existingForks -numberOfReposToDo ${{ env.numberOfReposToDo }} -access_token "${{ secrets.ACCESS_TOKEN }}" -access_token_destination ${{ steps.get_workflow_token.outputs.token }}
