name: Get actions that use the OSS Scan action

on:
  
  push: 
    branches: 
      - main
    paths:
      - .github/workflows/ossf-scan.yml
      - .github/workflows/ossf-scan.ps1

  schedule:
    - cron: '15 10 * * *'

  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get App Token
        id: get_workflow_token
        uses: rajbos-actions/workflow-application-token-action@v2.1.0
        with:
          application_id: 264650
          application_private_key: ${{ secrets.Automation_App_Key }}
          organization: actions-marketplace-validations
          
      - shell: pwsh
        name: Run reporting script
        run: |
           $actions=(cat status.json | ConvertFrom-Json)
           Write-Host "Found [$($actions.Length)] actions in the datafile"
           $numberOfReposToDo = $actions.Length
           ./.github/workflows/ossf-scan.ps1 -actions $actions -numberOfReposToDo $numberOfReposToDo -logSummary "$($env:GITHUB_STEP_SUMMARY)" -access_token "${{ secrets.ACCESS_TOKEN }}" -access_token_destination ${{ steps.get_workflow_token.outputs.token }}
