name: Run Pester tests

on:
  push:

defaults:
  run:
    shell: pwsh

jobs:
  pester-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current actions list
        run: |
          curl "${{ secrets.BLOB_SAS_TOKEN }}" > actions.json
      
      - name: Run Pester Tests
        run: Invoke-Pester -Output Detailed
