# Fork new action repos
# Get new data from Dependabot
# Store the data in the repo for later use

name: Analyze

on:
  push:
    paths:
      - .github/workflows/pipeline.yml
      - .github/workflows/functions.ps1
      - .github/workflows/repoInfo.ps1
      - .github/workflows/library.ps1

  schedule:
    - cron: '*/60 * * * *'

  workflow_dispatch:

env:
  numberOfReposToDo: 100
  numberOfReposToDoRepoInfo: 100
    
jobs:
  check-em-all:
    concurrency: there-can-be-only-one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current actions list
        run: |
          curl "${{ secrets.BLOB_SAS_TOKEN }}" > actions.json
          
      - shell: pwsh
        name: Gotta check 'em all
        run: |
           $actions=(cat actions.json | ConvertFrom-Json)
           Write-Host "Found [$($actions.Length)] actions in the datafile"
           Install-Module -Name PSGraphQL -Repository PSGallery -Scope CurrentUser -Allowclobber -Force
           Install-Module -name powershell-yaml -Force -Repository PSGallery -Scope CurrentUser -Allowclobber
           # fork repos and load Dependabot status
           ./.github/workflows/functions.ps1 -actions $actions -numberOfReposToDo ${{ env.numberOfReposToDo }} -access_token "${{ secrets.ACCESS_TOKEN }}"
           # get repo information
           ./.github/workflows/repoInfo.ps1  -actions $actions -numberofReposToDo ${{ env.numberOfReposToDoRepoInfo }} -access_token "${{ secrets.ACCESS_TOKEN }}"

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.email "github_token@github.com"
            git config --global user.name "GITHUB_TOKEN"
            
            git add status.json
            git commit -m "Update status.json"
            git push
          else
            echo "Nothing to commit"
          fi
