name: Cleanup repos
on:
  workflow_dispatch:
    
jobs:
  cleanup-all-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - shell: pwsh
        name: Run reporting script
        run: |
           ./.github/workflows/cleanup-all-repos.ps1 -numberOfReposToDo 4000 -access_token "${{ secrets.ACCESS_TOKEN }}"

      