# report the data stored in the repository
name: Generate report

on:
  
  push: 
    branches: 
      - main
    paths:
      - .github/workflows/report.yml

  schedule:
    - cron: '1 9 * * *'

  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - shell: pwsh
        name: Run reporting script
        run: |
           $actions=(cat status.json | ConvertFrom-Json)
           Write-Host "Found [$($actions.Length)] actions in the datafile"
           ./.github/workflows/report.ps1 -actions $actions -logSummary "$($env:GITHUB_STEP_SUMMARY)"

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: report
          path: VulnerableRepos-**.txt