# report the data stored in the repository
on:
  
  push: 
    branches: 
      - main    

  schedule:
    - cron: '*/60 * * * *'

  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - shell: pwsh
        run: |
           $actions=(cat status.json | ConvertFrom-Json)
           Write-Host "Found [$($actions.Length)] actions in the datafile"
           ./.github/workflows/report.ps1 -actions $actions -logSummary "$($env:GITHUB_STEP_SUMMARY)"
